<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use TCPDF;

class DocumentManagerController extends Controller
{
    public function storeReport(Request $request)
    {
        $request->validate([
            'report_type' => 'required',
            'data' => 'required'
        ]);

        $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        
        $pdf->SetCreator('CaliCrane System');
        $pdf->SetAuthor('Reporting & Analytics Team');
        $pdf->SetTitle($request->report_type . ' Report');
        $pdf->SetSubject('Automatically Generated Report');
        
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        
        $pdf->AddPage();
        $pdf->SetFont('helvetica', '', 10);
        
        $html = '
        <style>
            body { font-family: helvetica; }
            .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 15px; }
            .header h1 { margin: 0; color: #333; font-size: 18px; }
            .summary { background: #f5f5f5; padding: 10px; margin-bottom: 20px; border-radius: 5px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th, td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 9px; }
            th { background-color: #e5e5e5; font-weight: bold; }
            .footer { margin-top: 20px; font-size: 8px; color: #666; text-align: center; }
        </style>
        
        <div class="header">
            <h1>' . $request->report_type . ' REPORT</h1>
            <p>Generated on: ' . date('F d, Y H:i:s') . '</p>
        </div>
        
        <div class="summary">
            <p><strong>Generated by:</strong> Reporting & Analytics System</p>
            <p><strong>For:</strong> Document and File Manager</p>
        </div>
        
        <h3 style="margin-bottom: 10px; font-size: 12px;">Report Details</h3>
        <table>
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>';
        
        foreach ($request->data as $key => $value) {
            $html .= '<tr>
                <td>' . ucfirst(str_replace('_', ' ', $key)) . '</td>
                <td>' . $value . '</td>
            </tr>';
        }
        
        $html .= '</tbody>
        </table>
        
        <div class="footer">
            <p>This is an automatically generated document. Do not distribute without authorization.</p>
        </div>';

        $pdf->writeHTML($html, true, false, true, false, '');
        $pdf->SetProtection(['print', 'copy'], 'document', 'admin');
        
        $filename = $request->report_type . '_' . time() . '.pdf';
        $filePath = 'document_manager/' . $filename;
        $pdfContent = $pdf->Output($filename, 'S');
        
        Storage::put($filePath, $pdfContent);
        
        return response()->json([
            'success' => true,
            'message' => 'Report successfully sent to Document Manager',
            'filename' => $filename
        ]);
    }
}